### ISSUE TITLE
Example Doesn't Work [13835]

### ISSUE THREAD

**Issue by esgungor** [eProsima/Fast-DDS-statistics-backend#146]
Hello, I try to figure out Fast-DDS Statistics - Backend. The example project is partially working.
Topic HelloWorldTopic update info.
```bash
DataReader with GUID 01.0f.14.4b.c8.6d.13.b6.01.00.00.00|0.0.1.4 update info.
Participant with GUID 01.0f.14.4b.04.6e.9a.96.01.00.00.00|0.0.1.c1 update info.
DataWriter with GUID 01.0f.14.4b.04.6e.9a.96.01.00.00.00|0.0.1.3 discovered.
```
The service discovery feature is working. However, I cannot see latency on publication process.
```bash
Fast DDS Latency of HelloWorld topic: [2022-02-11 08:48:07.406, nan μs]
Publication throughput of Participant Participant_pub: [2022-02-11 08:48:07.407, nan B/s]
```
Probably it cannot take any data about latency.

> If for a given bin, the Fast DDS Statistics Backend has no data, the value returned will be the one supplied by [std::numeric_limits<double>::quiet_NaN](https://en.cppreference.com/w/cpp/types/numeric_limits/quiet_NaN).

Thanks.

**Comment by rsanchez15** [comment]
Hi @esgungor,

The problem you may have is that the statistics module is not enabled in Fast DDS. By default the statistics are disabled so as not to overload the network with additional messages, so you need to enable them manually in the Fast DDS compilation process. When compiling Fast DDS use this CMake option to enable statistics.: `FASTDDS_STATISTICS=ON`.

Once you have done this, in each environment (console) in which you launch Fast DDS publishers and subscribers you must set an environment variable to enable the report of statistics from your Fast DDS entities. Run the following command to do this:

```bash
export FASTDDS_STATISTICS="HISTORY_LATENCY_TOPIC;NETWORK_LATENCY_TOPIC;PUBLICATION_THROUGHPUT_TOPIC;SUBSCRIPTION_THROUGHPUT_TOPIC;RTPS_SENT_TOPIC;RTPS_LOST_TOPIC;HEARTBEAT_COUNT_TOPIC;ACKNACK_COUNT_TOPIC;NACKFRAG_COUNT_TOPIC;GAP_COUNT_TOPIC;DATA_COUNT_TOPIC;RESENT_DATAS_TOPIC;SAMPLE_DATAS_TOPIC;PDP_PACKETS_TOPIC;EDP_PACKETS_TOPIC;DISCOVERY_TOPIC;PHYSICAL_DATA_TOPIC"
```

This is already done in the source C++ code of the HelloWorld example, but it is necessary if you launch separate nodes that you want to monitor. 

We will update the Statistics Backend documentation as soon as possible to have all this build and launch processes well documented. 

As an additional suggestion, you could download and use the Fast DDS Monitor to check that your nodes are publishing statistics messages. This is a graphical tool available [here](https://www.eprosima.com/index.php/products-all/eprosima-fast-dds-monitor). It has a portable version (AppImage) for Ubuntu that does not require installation. It also has installers for Windows and Linux platforms.

**Comment by esgungor** [comment]
Thanks for the answer, yes I figured out the situation with the eProsima Suite Docker image. Documentation updates would be nice for development purposes use-cases with statistics backend.
